"use client";
import Particles from "@/components/Particles";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Adamina, Anybody } from "next/font/google";

import "./globals.css";
import { Flag } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const adamina = Anybody({
  weight: "400",
  variable: "--font-anybody",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ position: "relative" }}>{children}</body>
    </html>
  );
}

export { geistSans, geistMono, anton, adamina };
